name: Run KineticGreen Scraper

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Setup Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v2
        with:
          chromedriver-version: latest

      - name: Run script
        env:
          PATH: /usr/local/share/chrome-driver:$PATH
        run: |
          python kineticgreen_scraper.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: |
            kineticgreen_showrooms_new_*.csv
