name: Run KineticGreen Scraper

on:
  workflow_dispatch:

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Google Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Get Chrome version
        id: get_chrome_version
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -1)
          echo "CHROME_VERSION=$CHROME_VERSION" >> $GITHUB_OUTPUT

      - name: Download matching Chromedriver
        run: |
          CHROME_VERSION=${{ steps.get_chrome_version.outputs.CHROME_VERSION }}
          echo "Detected Chrome version: $CHROME_VERSION"
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
          echo "Matching Chromedriver version: $DRIVER_VERSION"
          curl -s -o chromedriver.zip "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver.zip
          chmod +x chromedriver
          sudo mv chromedriver /usr/local/bin/

      - name: Run script
        run: python kineticgreen_scraper.py

      - name: Upload CSV artifact
        uses: actions/upload-artifact@v4
        with:
          name: scraped-data
          path: |
            kineticgreen_showrooms_new_*.csv
