name: Scrape Kinetic Green Dealers

on:
  workflow_dispatch:  # Manual trigger via GitHub UI

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    env:
      EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt update
          python -m pip install --upgrade pip
          pip install selenium pandas beautifulsoup4 requests

      - name: Run scraper script
        run: python test.py  # Rename this to your actual filename

      - name: Send CSV via email
        run: |
          python send_mail.py
